# Generated by Django 5.1.3 on 2024-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORTATION', 'Transportation'), ('CLOTHING', 'Clothing'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills'), ('INSURANCE', 'Insurance'), ('HEALTHCARE', 'Healthcare'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SKINCARE', 'Skincare'), ('GYM', 'Gym'), ('GROCERY', 'Grocery'), ('FAMILY', 'Family'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
