# Generated by Django 5.1.3 on 2024-11-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bill_saving_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='description',
            new_name='item',
        ),
    ]
