# Generated by Django 5.1.3 on 2024-11-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_saving_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_images'),
        ),
    ]
