# Generated by Django 5.1.3 on 2024-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_wishlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('MAKE UP', 'Makeup'), ('CLOTHING', 'Clothing'), ('SHOPPING', 'Shopping'), ('HEALTHCARE', 'Healthcare'), ('SKINCARE', 'Skincare'), ('BAG', 'Bag'), ('GROCERY', 'Grocery'), ('FAMILY', 'Family'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
