# Generated by Django 5.1.3 on 2024-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_wishlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('GYM', 'Gym'), ('LIFE INSURANCE', 'Life Insurance'), ('ALLOWANCE', 'Allowance'), ('BAHAY', 'Bahay'), ('APARTMENT', 'Apartment'), ('EMERGENCY FUND', 'Emergency Fund'), ('SAVINGS', 'Savings'), ('EXTRA', 'Extra'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
